# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

############
# seed candidates
############

if !Candidate.count.zero?  #if there are NOT zero candidates

  Candidate.destroy_all

  candidates = [
    [1, "Hillary Clinton", "Democratic", "Former Secretary of State"], #Clinton is first because she represents the party that currently controls the White House.
    [2, "Donald Trump", "Republican", "Businessman"],
    [3, "Gary Johnson", "Libertarian", "Former New Mexico Gov."],
    [4, "Jill Stein", "Green", "Dr."],
    [5, "Evan McMullin", "Independent Conservative", "Former House GOP Conference Policy Director"]
  ]

  candidates.each do | a, b, c |
    Candidate.create(id: a, name: b, party:c, title:d)
  end

end

###############
# seed issues
###############

if !Issue.count.zero?

  Issue.destroy_all

  issues = [
    ["Afghanistan"],
    ["Agriculture"],
    ["Budget & Fiscal Policy"],
    ["Campaign & Electoral Reform"],
    ["China"],
    ["Civil Rights"],
    ["Criminal Justice & Police Reform"],
    ["Cuba"],
    ["Economy"],
    ["Education"],
    ["Energy"],
    ["Environment"],
    ["Family Issues"],
    ["Financial Regulation"],
    ["Food Policy"],
    ["Government Reform"],
    ["Guns"],
    ["Healthcare"],
    ["Immigration"],
    ["Infrastructure"],
    ["Iran"],
    ["Iraq"],
    ["Islands & Territories"],
    ["Israel"],
    ["Medicare/ Medicaid"],
    ["North Korea"],
    ["Public Health"],
    ["Russia"],
    ["Social Issues"],
    ["Social Security"],
    ["Syria"],
    ["Taxes"],
    ["Technology"],
    ["Terrorism"],
    ["Trade"],
    ["Veterans"],
  ]

  issues.each do | a |
    Issue.create(issname: a)
  end

end


###############
# seed positions
###############

if !Position.count.zero?

  Position.destroy_all

  positions = [
    [1,1, "Clinton has supported Obama's move to maintain a larger military presence in Afghanistan than he intended; she suggests that she will continue the current American trajectory in Afghanistan."],
    [2,1, "Trump supports leaving a residual force in Afghanistan."],
    [3,1, "Johnson opposes further military involvement in Afghanistan and supports withdrawing combat troops, but would not rule out leaving American military bases behind."],
    [4,1, "Stein supports withdrawing entirely from Afghanistan."],
    [5,1, nil],
    [1,2, "Clinton has called for the government to expand resources for rural businesses and communities. She supports: a) increasing the number of Rural Business Investment Companies (RBICs) and expanding access to equity capital; b) simplifying regulations on community banks; c) strengthening relevant tax credits, USDA grants, agricultural training programs, and farmers’ market promotion programs; and d) expanding the safety net for cases where farmers and ranchers face economic and climate challenges."],
    [2,2, "Trump supports the use of ethanol and biofuel. He also supports the Renewable Fuel Standard (RFS) set by Congress. Other than that, Trump has largely stayed mum on agricultural issues, although he has recently announced a team of agricultural advisers."],
    [3,2, "Johnson has supported more local stewardship of agriculture, and opposed farm subsidies. Citing public safety as an area of government concern, he favors labels for GMO products."],
    [4,2, "Stein supports 'organic and regenerative agriculture, permaculture, and sustainable forestry.' She opposes 'agri-business'."],
    [5,2, nil],
    [1,3, "Clinton has suggested that her approach to the federal budget would mirror President Obama's, namely increases in federal spending and taxes, mostly on wealthier Americans and corporations. On the Federal Reserve, she will also continue the Obama administration's paradigm, from appointing governors who support more oversight of the financial industry to supporting the 'dual mandate' of maximizing employment while stabilizing prices. But she has recently endorsed liberal reforms like removing bankers from the boards of regional Fed banks."],
    [2,3, "Trump's policies regarding the federal budget and fiscal policy largely amount to campaign platitudes. He has pledged to cut the national debt to zero in eight years, although he has not suggested significant trims to major items like Social Security, Medicare, Medicaid, and defense. Controversially, the self-proclaimed 'king of debt' has suggested that he would negotiate the value of U.S. debt, which many experts have interpreted as openness to defaulting on the debt. Trump has suggested that he would fire Federal Reserve Chair Janet Yellen, and that he would be open to auditing the Federal Reserve. Meanwhile, he has spoken in favor of low interest rates, both as a candidate and in his professional life as a real estate developer. He has also spoken in favor of returning to the gold standard."],
    [3,3, "As he did in 2012, Johnson proposes to submit a balanced budget his first year in office. He pledges to cut the roughly $600 billion deficit without raising taxes (he favors the FairTax plan). Johnson's plan proposes a 20 percent cut in spending across the board, and even a 43 percent cut in major items like military spending, Medicare, and Medicaid. Johnson opposes any form of subsidies or bailouts, even for states. In 2011, Johnson suggested that the federal government create a process for state bankruptcies. He favors auditing the Federal Reserve or abolishing it and returning to the gold standard."],
    [4,3, "Stein proposes a dramatic increase in the federal budget for a 'Green New Deal', especially in job creation programs and green resources. She personally responded to a Political Courage Test on the Vote Smart website in 2012. There, she indicated that she would generally maintain current funding levels for agriculture, international aid, medical and scientific research, and the UN. She would slightly increase funds for arts and education programs. She proposes to slash America's military budget by at least half, and also decrease the homeland security budget. The Green Party's platform calls for at least $2.2 trillion in infrastructure spending over the next 5 years, paid for in no small part by nationalizing the nation's Federal Reserve banks."],
    [5,3, nil],
    [1,4, "On this issue, Clinton has adopted a liberal posture in line with the positions of her primary rival, Vermont Sen. Bernie Sanders. She endorsed the idea of overturning the Citizens United decision, through the appointment of more liberal Supreme Court justices or a constitutional amendment. She proposes federal legislation to demand outside groups to publicly disclose political spending, and regulations for federal government contractors and publicly traded companies to do so. She also proposes a small-donor matching system for congressional and presidential candidates, including limits on the size of donations and matching funds.  She believes in universal, automatic voter registration; a national standard of at least 20 days of early voting; restored voting rights for ex-felons; and making Election Day a federal holiday."],
    [2,4, "Trump has stayed mum on how he plans to address campaign finance reform, although his party opposes tightening contribution limits. In the primary campaign, he has not only opposed 'PACs', or political action committees, but also expressed openness to campaign finance reform. Trump has stated that he self-funded his primary campaign, cementing his independence from lobbyists, special interests, and donors like he once was. But he has also supported the idea that people could donate to campaigns, so long as there are no strings attached. For example, he quietly sent out fundraising emails and allowed people to donate through his campaign website. He collected millions of dollars throughout the primary, and he plans on collecting much more throughout the general election."],
    [3,4, "Johnson does not favor public financing of campaigns. When it comes to electoral reform, he has supported allowing ex-felons to vote and opposed requiring voter IDs."],
    [4,4, "Stein has proposed a radical overhaul of the electoral process. She calls for the abolition of the Electoral College, and the election of presidents through the popular vote with a ranked-choice voting system. She also proposes 'proportional representation' in Congress, or changing the process by which districts are determined. Indeed, she calls for non-partisan commissions to oversee elections. She believes that all qualified candidates should have equal access to the airways and to open debates. On campaign finance, she proposes a constitutional amendment that eliminates the doctrine of corporate personhood (as in the Citizens United decision). She has called for full public financing of elections. On the voter side, Stein proposes restoring voter rights to offenders, even while in prison; enacting same-day voter registration; and making Election Day a federal holiday."],
    [5,4, nil],
    [1,5, "Clinton wants to enhance diplomatic ties with China while exerting pressure over issues like North Korea’s nuclear program, cybersecurity, and its man-made islands in the South China Sea.   A frequent critic of China's human rights record, she wants to especially hold China accountable on that front.  She made her 1995 'women’s rights are human rights' speech in Beijing."],
    [2,5, "In his signature populist tone, Trump has proposed a protectionist tariff of 45 percent on Chinese exports. He also pledges to label China as a currency manipulator and take 'swift, robust and unequivocal' action against Chinese piracy, counterfeit American goods, and theft of American intellectual property. He has condemned China's 'illegal export subsidies and lax labor and environmental standards.' In a recent speech, Trump proclaimed, 'I am going to instruct the U.S. Trade Representative to bring trade cases against China, both in this country and at the WTO. China's unfair subsidy behavior is prohibited by the terms of its entrance to the WTO, and I intend to enforce those rules… If China does not stop its illegal activities, including its theft of American trade secrets, I will use every lawful presidential power to remedy trade disputes, including the application of tariffs consistent with federal law.'' Trump also proposes to strengthen the American military presence in the East and South China Seas, particularly in light of the development of controversial man-made islands."],
    [3,5, "Johnson supports enhancing diplomatic ties with China in order to address North Korea’s nuclear program."],
    [4,5, "Stein has called for enhancing diplomatic ties with China, and re-negotiating trade deals with them in a manner that reflects the 'Green New Deal' agenda.  She does not support putting diplomatic pressure or sanctions in response to developments in the South China Sea."],
    [5,5, "McMullin supports enhancing diplomatic pressure to China in order to address North Korea’s nuclear program."],
    [1,6, "Clinton has been a civil rights advocate for decades. In this election, she has called out the 'systemic racism' in education, employment, and elsewhere. She said in a debate that the United States need 'a new New Deal for communities of color'. Similarly, she has been a staunch advocate for the rights of women and minorities, from education to employment and beyond."],
    [2,6, "Trump has adopted positions that have led many to call him a racist and xenophobe, from supporting racial profiling to criticizing the Black Lives Matter movement. However, he has also opposed LGBT discrimination and gender inequity in the military. He has also expressed support for affirmative action, noting that there could be a time when it is no longer necessary."],
    [3,6, "Johnson has a very liberal view on civil liberties and civil rights."],
    [4,6, "Stein opposes the 'War on Drugs' and drug prohibition; she wants to release nonviolent drug offenders from prison. She calls for the elimination of mandatory minimums, mass incarceration, the death penalty, and the 'prison-industrial complex'. In solidarity with the Black Lives Matter movement, she calls for the end of 'police brutality… and institutional racism within our justice system.' To that end, she proposes the demilitarization of police, ending SWAT teams and no-knock raids for drugs and serving papers, establishing police review boards, and requiring outside investigators to handle 'killing or brutality by the police'."],
    [5,6, nil],
    [1,7, "On this issue, Clinton has adopted a liberal posture in line with the positions of her primary rival, Vermont Sen. Bernie Sanders. She endorsed the idea of overturning the Citizens United decision, through the appointment of more liberal Supreme Court justices or a constitutional amendment. She proposes federal legislation to demand outside groups to publicly disclose political spending, and regulations for federal government contractors and publicly traded companies to do so. She also proposes a small-donor matching system for congressional and presidential candidates, including limits on the size of donations and matching funds. She believes in universal, automatic voter registration; a national standard of at least 20 days of early voting; restored voting rights for ex-felons; and making Election Day a federal holiday."],
    [2,7, "Trump has often talked about being tough on crime, and has adopted the moniker of the 'law and order candidate'. He has often talked about giving power 'back to the police', and ending the 'war on police'. And he has also favored capital punishment for decades. Although he has expressed support for private prisons and profiling, other details about his hawkish stance are scarce."],
    [3,7, "Johnson supports private prisons but, despite earlier support, opposes the death penalty. Much of Johnson's other rhetoric on crime ties to his opposition to the 'War on Drugs'; he argues that a lot of violent crime stems from the prohibition of certain drugs, much like the bootleggers of Prohibition."],
    [4,7, "Stein proposes a dramatic increase in the federal budget for a 'Green New Deal', especially in job creation programs and green resources. She personally responded to a Political Courage Test on the Vote Smart website in 2012. There, she indicated that she would generally maintain current funding levels for agriculture, international aid, medical and scientific research, and the UN. She would slightly increase funds for arts and education programs. She proposes to slash America's military budget by at least half, and also decrease the homeland security budget. The Green Party's platform calls for at least $2.2 trillion in infrastructure spending over the next 5 years, paid for in no small part by nationalizing the nation's Federal Reserve banks."],
    [5,7, nil],
    [1,8, "Clinton supports the Obama administration's recent move to loosen the trade and travel embargo on Cuba."],
    [2,8, "Trump has expressed openness to loosening the trade and travel embargo with Cuba; indeed, the real estate mogul has suggested that he would like to build a hotel in Cuba."],
    [3,8, "Johnson opposes the decades-long American sanctions on Cuba, especially the recently-loosened embargo."],
    [4,8, "Stein supports the Obama administration's recent move to loosen the trade and travel embargo on Cuba."],
    [5,8, nil],
    [1,9, "Clinton's plan pledges incentives for corporations to invest in the United States and American employees, share profits with employees. Meanwhile, she proposes to rescind tax relief and other benefits for companies that outsource jobs abroad, and impose a new exit tax on companies that move overseas. She also supports raising the minimum wage to $12/hour, and praises those states and communities that have raised their respective minimum wages to $15/hour. The New York Times describes her economic philosophy as 'inclusive capitalism': namely, it 'calls on corporations to invest in employees, communities and the environment rather than relying on short-term profits that increase shareholder value.'"],
    [2,9, "Trump has adopted a supply-side position on the economy, arguing that reducing regulations and simplifying the tax code would encourage businesses to hire more American employees. But his economic agenda also includes a populist, protectionist component. He has repeatedly proposed tariffs on exports from China and Mexico, two of his favorite campaign targets. Specifically, he has proposed 15-35 percent tariffs on goods from companies that move their operations to Mexico, like Ford and Carrier. Furthermore, he has frequently stated that he wants to renegotiate international trade deals to benefit American workers, comparing those deals to business deals that would be included in his book, The Art of the Deal."],
    [3,9, "A libertarian and supply-sider, Johnson opposes any form of federal stimulus, jobs program, or tariffs. He believes that a balanced budget and a FairTax system will help encourage businesses to create jobs."],
    [4,9, "The centerpiece of Stein's platform calls for a 'Green New Deal' that would transition the nation to 100 percent clean energy by 2030. The plan calls for a full employment program, including Works Progress Administration-style direct public employment, to create 20 million jobs in 'greening' the nation; she calls for a living-wage job to be a right, along with health care and education. She supports a $15/hour minimum wage. She aims to 'ensure that any worker displaced by the shift away from fossil fuels will receive full income and benefits as they transition to alternative work.'"],
    [5,9, "McMullin recently did a brief interview with Bloomberg where he discussed economic issues. On poverty, he has stated that he would focus on more local solutions on the state level rather than 'one-size-fits-all programs run out of Washington', such as those that President Lyndon Johnson advocated as part of his 'Great Society' program. He has suggested that he would focus on 'welfare cliffs' - where recipients of government reach a certain income level and thus become ineligible for benefits. Despite the lack of details in his proposals as of yet, he predicts that his plans can spur American GDP growth to 2 percent. GDP growth has averaged 1.8 percent over the last 15 years."],
    [1,10, "On the pre-kindergarten level, Clinton supports making access to preschool universal for every 4-year-old. On the K-12 level, she initially supported the Bush administration's No Child Left Behind program, but she criticized the administration's handling of it. She supports Common Core, but not the paradigm that 'teaches to the test'. She supports charter schools and opposes education vouchers. On the collegiate level, she supports making community colleges tuition-free, like President Obama does, and making public schools’ tuition debt-free. She also proposes a $350 billion plan that she has called the 'New College Compact'. As part of the plan, she calls for schools to be accountable in reining in costs and improving completion rates; for expanded work opportunities to students; and for crackdowns on 'the abusive practices of for-profit colleges'. For existing student debt, she has called for a three-month moratorium on student loan payments, and then allowing graduates to refinance loans at current rates. She supports deferring loans for entrepreneurs; forgiving student loans for public/national service, and an income-based repayment program that will forgive college debt 'after 20 years – and 10 years if a borrower works in the public interest'."],
    [2,10, "Trump proposes to eliminate the federal Department of Education. On the state and local level, where he believes that all matters pertaining to education should be handled, Trump believes in school voucher systems and school choice. He opposes federal involvement in student loans."],
    [3,10, "Johnson proposes to eliminate the federal Department of Education. On the state and local level, where he believes that all matters pertaining to education should be handled, Johnson believes in school voucher systems like the one he sought to implement as governor of New Mexico. He opposes federal involvement in student loans, but suggested that he would consider lowering interest rates on student loans if he were president."],
    [4,10, "Stein favors tuition-free public education from pre-school through university; she proposes increasing federal funding of public schools and grants 'to encourage metropolitan desegregation plans based on socioeconomically balanced schools.' She opposes Common Core and 'teaching to the test'; she also opposes charter schools. Despite her support for expanding federal resources, she believes that educational decisions should be made at the local level. On the college level, she proposes cancelling student debt 'with the stroke of a pen'."],
    [5,10, "McMullin opposes Common Core and increased federal involvement in the national education system. He favors charter schools, magnet schools, and more local solutions. Beyond that, details on his position are scarce."],
    [1,11, "A strong believer in climate change, Clinton has embraced an ambitious agenda for the United States to accelerate its transition away from fossil fuels. She has called for the installation of half a billion solar panels by 2021, and for there to be enough renewable energy to power every American home by 2027. By that same year, her goal is for at least a third of American electricity to come from renewable sources. To that end, she supports tax credits for wind energy and other sources. She pledges to launch a $60 billion Clean Energy Challenge. Clinton supports renewing permits for existing nuclear power plants. She supports ethanol and strengthening the Renewable Fuel Standard (RFS), which requires that transportation fuel sold in the United States contain a minimum volume of renewable sources. She supports fracking, under limited circumstances, but opposes the Keystone XL pipeline. She also opposes drilling in the Arctic National Wildlife Refuge (ANWR)."],
    [2,11, "Trump proposes an 'all of the above' energy policy that he predicts will achieve 'complete energy independence'. While he is open to the exploration and expansion of renewable energy, he argues that it should ultimately occur under market forces. He supports the Renewable Fuel Standard (RFS), which requires that transportation fuel sold in the United States contain a minimum volume of renewable sources. But he opposes regulations that promote renewable energy over natural gas and coal, including the EPA's Clean Power Plan and the Department of the Interior's current moratorium on coal mining permits. He does favor expanding resources for oil, coal, and natural gas. For example, he supports the Keystone XL pipeline and opening the Outer Continental Shelf to exploration."],
    [3,11, "Johnson believes in a more laissez-faire approach to energy. He favors the research and use of alternative sources of energy, along with coal-fired and nuclear energy, but opposes federal subsidies for any form of energy. He is conditionally in favor of fracking, even though he has reservations; he prefers for more research to be done. In 2012, he said that he opposed the Keystone XL pipeline only if eminent domain was involved."],
    [4,11, "Stein is a staunch opponent of fossil fuels and natural gas, subsidies for those sources of energy, and whatever facets of American infrastructure are reliant on them. She opposes fracking, tar sands, offshore drilling, oil trains, mountaintop removal, natural gas pipelines, and uranium mines; nuclear power and subsidies. Instead, she proposes an 'emergency Green New Deal' that would transition the nation to 100 percent clean energy by 2030. She aims to 'ensure that any worker displaced by the shift away from fossil fuels will receive full income and benefits as they transition to alternative work.' Similarly, federal funds that have been directed towards non-'green' sources would be redirected towards renewable sources. She also proposes a 'greenhouse tax' and enacting 'energy democracy based on public, community and worker ownership of our energy system'."],
    [5,11, "While details on his plan are scarce, McMullin seems to support an all-of-the-above energy policy that promotes the development of all kinds of energy, from fossil fuels to nuclear power and renewables."],
    [1,12, "A strong believer in climate change, Clinton wants to build on President Obama's program and ideas. She supports the Obama Administration's proposed Clean Power Plan, including the regulation of carbon emissions from power plants. She also supports Obama's goals in accordance with the Paris climate negotiations: namely, reducing greenhouse gas emissions by up to 30 percent in 2025, and over 80 percent by 2050, both relative to 2005 levels. She vehemently opposes what she views as the inhumane treatment of animals, from the use of antibiotics on farm animals to 'harmful' commercial breeding practices. Finally, she has called for national initiatives to eliminate lead poisoning within five years and clean up toxic brownfield sites."],
    [2,12, "Trump says that he is 'committed' to clean air and water, but he, like his party, favors environmental stewardship led by locals. He proposes the repeal of the EPA's Waters of the United States (WOTUS) rule, which largely defines what waterways and wetlands are subject to EPA and Army Corps of Engineers jurisdiction. His stance echoes the GOP platform's opposition to the rule, which Republicans view as a power grab. He has also highlighted the need for a new water infrastructure to be created. He opposes international climate deals like the Paris Climate Agreement, which he has pledged to re-negotiate; he also pledges to stop the flow of American tax dollars to U.N. climate initiative. Although Trump the candidate has denied climate change, Trump the real estate mogul recently acknowledged 'global warming and its effects' when he sought permission to build a sea wall to protect one of his golf courses in Ireland."],
    [3,12, "Johnson believes in both conservationism and global warming, and has cited the EPA as an effective government agency that protects Americans against pollution. But he generally believes that energy sources should be developed through the market. Recently, he has stated that he would be open to a carbon tax, as long as it is revenue-neutral."],
    [4,12, "Consistent with the name of her party, Stein is a staunch environmentalist. She refers to climate change as 'the greatest threat to humanity in our history' and worthy of a 'WWII-scale national mobilization'. Her platform calls for investments in 'clean air, water, food, and soil for everyone.' Details are scarce, but she does supports a ban on pesticides like neonicotinoids. She also calls for 'environmental justice laws and measures to ensure that low-income and communities of color are not disproportionately impacted by harmful pollution and other negative environmental and health effects.'"],
    [5,12, nil],
    [1,13, "Clinton has called for paid family and medical leave of up to 12 weeks, with at least a two-thirds replacement rate; she has called for paying for the plan through taxes on the wealthy. She also supports increased investment in child care."],
    [2,13, "Trump has stated that 'you have to be careful' about paid family leave, speaking from his perspective as a businessman. However, he supports allowing parents to fully deduct the average cost of childcare spending from their taxes."],
    [3,13, "Johnson opposes federally guaranteed paid family and medical leave. He seems to want to leave family issues to more local levels of government."],
    [4,13, "Stein favors federally guaranteed paid sick leave and family leave."],
    [5,13, nil],
    [1,14, "Time and again, Clinton has called for increased regulation of the financial sector, from the non-traditional 'shadow banking' sector to the traditional sector and its relations with the government.. She has staunchly defended the Dodd-Frank financial reform law, but she proposes building on it with new taxes on risky trades and high-frequency traders. She has opposed reinstating the Depression-era Glass-Steagall Act, which was repealed under her husband's administration, but her party's platform has called for its reinstatement. Moreover, she supports closing loopholes like the one that allows banks to invest in risky trades, and is open to prosecuting financial crimes. She is also open to the idea that regulators could reorganize or break up big banks."],
    [2,14, "Although Trump has frequently mocked the financial sector, especially hedge funds, on the campaign trail, he has not offered many specifics on how he would regulate the financial sector. But he has offered a couple of clues. He opposes the Dodd-Frank financial reform bill that President Obama signed into law. He supports reinstating Glass-Steagall, a Depression-era Act which separates commercial banking from speculative banking. The Act was repealed under legislation signed by President Clinton."],
    [3,14, "Johnson has largely stayed mum on the issue, although he has stated that he wants to repeal Dodd-Frank."],
    [4,14, "Stein favors a radical overhaul of the financial system. Stein favors reinstating Glass-Steagall, a Depression-era Act which separates commercial banking from speculative banking, and breaking up big banks. She also supports regulating all financial derivatives and requiring them to be traded on open exchanges. Finally, she wants to replace the Federal Reserve with public banks on the federal, state, and municipal levels, and 'democratize' monetary policy."],
    [5,14, nil],
    [1,15, "Clinton favors keeping federal food programs, like the Supplemental Nutrition Assistance Program (SNAP) program, funded. She also wants to increase local food options through different channels - grants that aim to connect consumers directly to farmers, increased funds for USDA marketing programs, and other non-specified avenues. She has indicated support for the use of genetically modified organisms (GMOs)."],
    [2,15, "Trump's stance on overall food policy is unclear, but he has vowed to cut federal assistance programs like SNAP (or food stamps). He also opposes mandatory labeling for genetically modified foods."],
    [3,15, "Citing public safety as a responsibility of government, Johnson favors labeling genetically modified organisms (GMOs)."],
    [4,15, "Stein heavily supports the labeling of genetically modified organisms (GMOs) and a moratorium on new GMOs."],
    [5,15, nil],
    [1,16, "Clinton seems to favor continuing and expanding on President Obama's regulatory approach. In short, she wants to expand government regulations in many areas, while she has said that several agencies need to be streamlined. In one debate, she cited the Department of Defense as one agency that should be scrutinized for waste, fraud, and abuse."],
    [2,16, "Trump has stated that one of his first acts in office will be to issue a temporary moratorium on new agency regulations, just like his running mate, Indiana Gov. Mike Pence, did at the beginning of his term. He has pledged to cancel all 'illegal and overreaching' executive orders; those probably refer to President Obama's. He has also promised to ask all federal agencies to prepare a list of all 'regulations they impose on American business, and rank them from most critical to health and safety to least critical. Least critical regulations will receive priority consideration for repeal.' Sample regulations that Trump has suggested for repeal include EPA rules regarding land use and coal mining permits."],
    [3,16, "As part of his plan to dramatically shrink the federal government, Johnson has indicated that he would cut entire federal departments like the Departments of Commerce, Education, and Housing and Urban Development. He is also a strong supporter of congressional term limits."],
    [4,16, "Stein favors congressional term limits. She also favors an expanded role for the federal government in domestic affairs and a significantly diminished military and homeland security budget. Her plan calls for nationalizing the nation's Federal Reserve banks and transforming Medicare into a single-payer system that will take over Obamacare and other recent health care reforms."],
    [5,16, nil],
    [1,17, "Clinton favors expanding background checks, and closing the gun show, Internet sales, and other loopholes. She has called for removing the gun lobby's legal protections and revoking licenses from dealers who break the law. She supports a strengthened Brady Bill and a reinstated assault weapons ban. She proposes making it illegal for domestic abusers, violent felons, and the mentally ill to purchase guns; and for people with clean records to buy guns for violent felons. She also favors barring people on the terrorist watch list and the no-fly list from purchasing weapons."],
    [2,17, "Trump opposes gun and magazine bans, despite his earlier support for a national assault weapons ban. He also opposes expanding background checks, gun-free zones, and banning the military from carrying arms on bases and at recruiting centers. He favors fixing the current background check system and better enforcing gun-related laws that are already on the books; he also supports a national right to concealed carry permits in all 50 states. In contrast with many in his party, he supports barring people on the terrorist watch list and the no-fly list from purchasing weapons."],
    [3,17, "Believing that the Second Amendment establishes an individual right for private citizens to bear arms, Johnson opposes limits on gun types or sizes. He also opposes gun-free zones and federal funding for research on gun violence. He recently stated that he is open to considering restrictions for the mentally ill. But he opposes restrictions for people on the no-fly and terror watch lists."],
    [4,17, "Calling the recent spate of mass shootings a 'national public health epidemic', Stein favors expanding gun regulation laws that are already on the books. She favors strengthening the Brady Bill, re-instituting waiting periods, and renewing the national assault weapons ban. Furthermore, she calls for federal funding for research on gun violence."],
    [5,17, "McMullin's position on this issue is vague as of yet, but he seems to take a more conservative position. He seems not to favor any expansive gun regulation, and yet is open to barring the ownership of guns among criminals, terrorists, and the mentally ill."],
    [1,18, "Clinton opposes the idea of repealing Obamacare; in fact, she is open to the idea of a 'public option'. She pledges to crack down on drug companies that charge excessive prices and stem rising out-of-pocket costs through tax credits and subsidies. She also favors extending access to Obamacare plans to all families, regardless of citizenship or immigration status, and doubling funding for community health centers. She supports further integrating telehealth systems into the health care system, especially in rural areas. She has also proposed expanding addiction and mental health treatment resources in rural areas. She has a long history of working to advance medical research as a first lady and a senator. She has long supported increasing federal funding for medical research, including stem cell research. In this election cycle, she has proposed initiatives to boost research for autism, HIV/AIDS, and Alzheimer's disease, among many other areas. She proposes an initiative that could provide a cure for Alzheimer's disease by 2025."],
    [2,18, "Trump opposes Obamacare and proposes its repeal. Although he has expressed support for a single-payer in the past, and for an individual mandate as recently as February 2016, he has reversed that position. Instead, the Trump plan calls for allowing health insurance companies to compete across state lines, and individuals to fully deduct insurance premium payments from their taxes. Individuals would also be able to use Health Savings Accounts (HSAs), contributions into which would be tax-free. On the provider side, he supports requiring price transparency, especially from doctors, clinics, and hospitals. On the pharmaceutical side, he supports international competition. He seems to support funding for medical research, but he has not indicated any clear policy proposals. He once called funding for Alzheimer's research 'a top priority,' but that was in a short answer to a campaign stop. (Full disclosure: he lost his father to Alzheimer's.)"],
    [3,18, "Johnson proposes repealing Obamacare, but he has not specified details about a replacement. He has vaguely proposed a more free-market oriented solution, along with tort reform. This is in line with his belief that health care should be handled at the state and local levels. He also opposes federal funds for stem cell research - and, ostensibly, other forms of medical research."],
    [4,18, "Stein wants to replace Obamacare with a Medicare-for-all single-payer plan."],
    [5,18, "McMullin opposes Obamacare, but has been vague about what his proposed alternative should be. He has suggested that the government reduce its role in healthcare, while he supports reforms that protect patients with pre-existing conditions."],
    [1,19, "Clinton vows to fight for the comprehensive immigration legislation, including a path to full and equal citizenship for the 11 million-plus undocumented immigrants in the country, that Obama has fought for. She also pledges to expand on Obama's executive actions on immigration, deportation, and work visas. She has critiqued the Obama administration on the 'inhumane' detention of children and other 'vulnerable' people. And she has pledged to help create a federal Office of Immigrant Affairs to both coordinate government policy on immigration and help immigrants as they settle into their communities. Finally, she has called for the United States to accept many more Syrian refugees than Obama has proposed - even as many as 65,000."],
    [2,19, "Trump has maintained a hardline position on immigration ever since he began his presidential bid. In his signature policy proposal, he calls for the construction of a wall across the entire southern border, and have Mexico either finance it or face new penalties. He has called for the deportation of undocumented immigrants - especially criminals - and ending guaranteed birthright for their children (he has expressed openness to keeping those 'Dreamers' who have served in the military). He has also called for a deportation of Syrian refugees that are already in the United States, and a ban on future ones. Indeed, he favors a temporary ban on Muslims from entering the country, and on immigration from 'areas of the world when there is a proven history of terrorism against the United States, Europe, or our allies'. Other elements of his hardline plan include tripling the number of ICE (Immigration and Customs Enforcement) agents; require businesses nationwide to use E-Verify; slash federal funding of 'sanctuary cities', and even restricting legal immigration, especially the flow of guest workers."],
    [3,19, "Johnson opposes Trump's hardline, protectionist policy proposals on immigration, from the border wall to deportation raids. He favors making it easier for immigrants - including non-criminal illegal immigrants - to get work visas and therefore pay taxes. He has supported a 'grace period' for undocumented immigrants, as well as a pathway to citizenship. He also supports the federal funding of sanctuary cities."],
    [4,19, "Stein favors a simple path to citizenship for non-criminal undocumented immigrants. She supports granting the children of illegal immigrants legal citizenship, and ending deportations."],
    [5,19, "McMullin favors a conservative plan that starts with securing the borders. Unlike Trump, he does not believe that a wall is necessary across the entire southern border. He indicates that some areas necessitate a wall, others a double wall, and still others none at all. He staunchly opposes Trump's proposal to deport all illegal aliens, and favors a path to citizenship for undocumented immigrants without criminal records."],
    [1,20, "Clinton has released a detailed plan that promises to address many facets of the nation's crumbling infrastructure - roads, bridges, waterways, dams, and water systems. She proposes a five-year, $250 billion plan for the nation's roads and bridges and another $25 billion to seed a national infrastructure bank. The plan projects that the bank will support an additional $225 billion in direct loans, loan guarantees, and other forms of credit enhancement. Her plan cites estimates by the White House Council of Economic Advisers that every $1 billion in infrastructure spending creates 13,000 jobs. By that math, the $500 billion projected under the plan will create 6.5 million jobs. Her plan also proposes an expanded and higher-capacity high-speed rail system; improvements in pedestrian and bicycle infrastructure across the nation; a national freight investment program; and universal broadband access by 2020."],
    [2,20, "In a sharp disagreement with many in his party, Trump favors increased spending on American infrastructure, especially on high-speed rail networks and mass transit. He has criticized the state of American infrastructure for years, often arguing that the funds that have been spent on American military ventures should have been spent here. He has repeatedly highlighted problems in America's roads, bridges, and airports, to name but a few. Details on his overall plan for infrastructure are scant, but he has suggested that he would double Clinton's $275 billion, five-year proposal."],
    [3,20, "Johnson has not announced any plans for America's infrastructure in this election cycle. But in 2011, he once suggested that private companies could be more involved in building and repairing roads."],
    [4,20, "Stein herself has not said much on the subject, but the platform of her party - who also nominated her for the presidency in 2012 - provides clues. The Green Party's platform calls for at least $2.2 trillion in infrastructure spending over the next 5 years, paid for in no small part by nationalizing the nation's Federal Reserve banks. It opposes expanding any part of America's infrastructure that relies on fossil fuels; for example, it demands a moratorium on widening roads. Instead, it advocates for expanding high-speed railway systems and local rail systems. and diverting highway funds to mass transit, bicycle ways, and pedestrian routes. The party also supports expanding broadband access and other advanced telecommunications."],
    [5,20, nil],
    [1,21, "Clinton supports the recent international deal with Iran on that country's controversial nuclear program. She supports loosening sanctions on Iran in exchange for limits on that program, but she also favors reimposing sanctions if the Iranian regime fails to comply with the agreement. Riffing on a Reagan-era slogan, she suggested that her policy towards Iran would be 'distrust and verify'."],
    [2,21, "Trump opposes the recent international deal with Iran over its nuclear program, and has expressed a desire to renegotiate in. Along with expressing support for tightened sanctions on Iran, he has stated that any deal should allow international inspectors to have 24-hour access to all nuclear sites in Iran. Furthermore, he has adopted a hawkish tone on potential provocations from Iran. In a recent rally where he pledged to modernize the missile defense system and expand the number of naval ships, he vowed that provocations from Iran will trigger a tough military response: 'they will be shot out of the water'."],
    [3,21, "Johnson has been largely vague when it comes to what the United States should do about Iran. But he has opposed the recent international deal over its nuclear program. In the previous election cycle, Johnson indicated that he prefers a more diplomatic approach to Iran, and that he would be willing to open up trade with that country."],
    [4,21, "Stein favors a more diplomatic approach to the Iranian nuclear question; accordingly, she favors loosening U.S. sanctions on the country and ending cyberattacks against it."],
    [5,21, "McMullin opposes the recent international deal on Iran's nuclear program, but believes that it must be enforced and built upon. He favors tightening sanctions on the country, and he is open to military action if Iran fails to comply."],
    [1,22, "Clinton does not support another deployment of American troops in Iraq. She does support providing more military and logistical support to local Arab forces and the Kurds. She also supports strengthening the American-led airstrikes against ISIS."],
    [2,22, "While Trump has frequently critiqued the American strategy in Iraq - and the handling of it by the Bush and Obama administrations - he has not fully indicated how he would address either Iraq or ISIS now. He has frequently suggested that America 'take the oil' from Iraq, but usually as a rhetorical device. He recently suggested that he would leave 'a certain group' of Americans behind in Iraq. Meanwhile, he seems to support more American airstrikes; he once said that he wanted to 'bomb the s--- out of ISIS.'"],
    [3,22, "Johnson opposed the Iraq War from its inception, and up until recently called for American troops to withdraw. However, he now supports declaring war on ISIS and continuing to 'knock ISIS out'."],
    [4,22, "Stein calls for a complete withdrawal from Iraq, as she has done for years."],
    [5,22, "Though McMullin served in Iraq, he believes the war itself was a mistake. Meanwhile, he has stated that he wants to 'pick up the pace' in developing a more rigorous strategy against ISIS. This includes providing more military support to allies in the region. He prefers that America use the CIA (in which he served) and Special Forces, and train local forces on the ground."],
    [1,23, "Clinton favors Washington, D.C. statehood. On Puerto Rico, she supports the recent bailout, with reservations over the interests of the oversight board. She has also supported Puerto Ricans' ability to determine their island's status for themselves, although she has not explicitly endorsed Puerto Rican statehood. Bill Clinton, at a campaign rally in the Virgin Islands, argued that people in American territories deserve equal treatment in terms of the economy, health care, and even voting rights."],
    [2,23, "Trump has not offered a clear position on Washington, D.C. statehood, but he has suggested that he would be open to it. He supports Puerto Ricans' ability to determine their island’s status for themselves; he has stated as such even after a referendum for Puerto Rican statehood passed. However, he opposes the recent bailout by Congress."],
    [3,23, "Johnson supports full statehood for Washington, D.C."],
    [4,23, "Stein supports full statehood for Washington, D.C. She has opposed the recent bailout of Puerto Rico, critiquing the island's 'colonial status' in the eyes of Washington."],
    [5,23, nil],
    [1,24, "Clinton has long advocated for Israel to reach a two-state solution with the Palestinians. She opposes the expansion of Israeli settlement and the boycott, divestment, and sanctions (BDS) movement. She supports recognizing Jerusalem as the capital of Israel and moving the American embassy there."],
    [2,24, "Like many American politicians, Trump has supported a two-state solution between Israel and the Palestinians, recognizing Jerusalem as the capital of Israel, and moving the American embassy to that city. But he diverges from a traditional American political stance both in terms of his approach and his policy proposals. He has talked about peace negotiations like a business deal. More significantly, he has suggested that Israel would be required to pay the United States back for its defense spending and foreign aid. He also opposes a pause in the construction of Israeli settlements in the West Bank."],
    [3,24, "Johnson favors a less involved American approach to Israel, particularly when it comes to how it deals with its neighbors; he also opposes sustaining American financial aid. But he supports continued 'strategic aid' to Israel."],
    [4,24, "A Reform Jew, Stein has called for ending military and economic support for the Israeli government, citing what she views as multiple violations of international law and human rights. She supports the boycott, divest, and sanctions (BDS) movement. She does not favor two-state solutions that have been in the works; rather, she favors going 'back to the drawing board' and pressuring the relevant parties to construct a deal. Steps that she has cited as progress include: 'discriminatory apartheid policies within the state of Israel, the removal of the Separation Wall, a ban on assassination, movement toward denuclearization, the release of all political prisoners and journalists from Israeli and Palestinian prisons, disarmament of non-state militias, and recognition of the right of self-determination for both Israelis and Palestinians.'"],
    [5,24, "McMullin believes that the United States should remain a staunch ally of Israel, but does not have a primary role in peace negotiations with the Palestinians. He is open to the two-state solution."],
    [1,25, "Clinton opposes Republican proposals to privatize, phase out, or block-grant Medicare and Medicaid. However, she is open to reforming the systems in ways that will streamline delivery systems and drive down drug costs. She calls for incentives for states to expand Medicaid. Indeed, she proposes that the federal government provide all of the expansion's cost for the first three years of implementation."],
    [2,25, "Trump opposes cuts to Medicare. He encourages allowing Medicare to negotiate directly with prescription-drug companies to reduce prices for the Medicare Part D benefit. He proposes block-granting Medicaid to the states."],
    [3,25, "Johnson proposes cutting federal Medicare and Medicaid funds by 43 percent and block-granting the rest to the states."],
    [4,25, "Stein wants to expand and reform Medicare into a single-payer system."],
    [5,25, nil],
    [1,26, "Clinton's strategy for dealing with North Korea, according to the New York Times, 'relies on a familiar formula of tightening sanctions against the government to pressure it to enter into multiparty negotiations on its nuclear program.' She oversaw a more hands-off approach to North Korea when she was Secretary of State."],
    [2,26, "Trump has controversially stated that South Korea and Japan should develop nuclear weapons if they are unwilling to pay the United States for security. He has also stated that the United States should put more pressure on China over North Korea; he has argued that China has 'total control' over North Korea. He has suggested that he would be willing to meet Kim Jong-un, if not for a state dinner. Other than these statements, he has not shared details about his agenda."],
    [3,26, "Johnson supports enhancing diplomatic ties with China in order to address North Korea's nuclear program."],
    [4,26, "On North Korea, Stein once said in a phone interview, 'We should lead by virtue of global agreements that also include us. We could get rid of many nukes as a first step because we're so far ahead' in possessing more nuclear weapons than the rest of the world."],
    [5,26, nil],
    [1,27, "Clinton has proposed a $10 billion 'Initiative to Combat America's Deadly Epidemic of Drug and Alcohol Addiction'. Clinton proposes re-focusing federal enforcement resources on violent crime rather than mere possession. She favors letting states be 'laboratories of democracy' when it comes to recreational use. She also favors re-scheduling marijuana from a Schedule I drug to a Schedule II drug; she supports use of and research into medical marijuana. When it comes to pandemics like Ebola and the Zika virus, she supports swift and expanded federal resources. For example, she critiqued Congress for not providing federal funds for appropriate health services to combat the Zika virus before going on its August recess."],
    [2,27, "Trump has not expressed clear positions on how he would handle different public health crises. He has been reluctant to discuss different addiction epidemics, from alcoholism (to which he lost his older brother) to heroin. In terms of the heroin epidemic, he has voiced support for local clinics, and then tied the crisis to his position on immigration. While he personally opposes recreational marijuana, he has suggested that the issue be handled on the state level; he does favor medical marijuana. He has not specifically addressed how he would handle a new pandemic, nor given any guidelines. But in response to the Ebola crisis in 2014, he tweeted that flights from West Africa should have been stopped, and that those afflicted with the virus should stay out of America. His tweets suggest that he would try to build a proverbial wall against the source of the pandemic, and that he would prefer quarantines to occur outside of the United States."],
    [3,27, "Johnson personally opposes the use of drugs and alcohol, but he does not believe in prohibition of either. Indeed, he believes that marijuana should be legalized, regulated, and taxed. He is willing to de-schedule that drug by executive order. He does not believe that it should be legal for anyone to drive while under the influence of marijuana. He favors lowering the legal drinking age to 18 or eliminating it altogether; he also opposes extra taxes on cigarettes."],
    [4,27, "Stein proposes legalizing marijuana and treating it as a public health issue rather than a criminal one. She has lambasted the War on Drugs, which she calls racist."],
    [5,27, nil],
    [1,28, "Clinton supports continuing present U.S. and E.U. sanctions on the Putin regime. In response to Russia's annexation of Crimea, which she would not recognize, she supports tightening sanctions and providing more funds, arms, and military training to Ukraine. She supports a no-fly zone in Syria that would also apply to Russia, an ally of the embattled Assad regime."],
    [2,28, "Much of Trump's controversial rhetoric on Russia has consisted of plaudits for President Vladimir Putin, a figure widely viewed as an adversary by Republicans. He has suggested that his administration would not only recognize the recent annexation of Crimea, but also loosen sanctions against the Putin regime. He even supports Russia's participation in international anti-terror - and particularly anti-ISIS - efforts. In a sharp break from the foreign policy paradigm that has guided administrations of both parties, he has attacked NATO. Earlier this year, he called it outdated because it is better suited to handle Cold War tensions than 21st-century threats that may come from non-state actors. More recently, he suggested that the United States should not automatically come to the defense of fellow NATO members unless those members 'fulfilled their obligations to us'. Article V of the NATO treaty indicates that an attack on one is an attack on all."],
    [3,28, "Johnson has opposed American engagement with Russia after its annexation of Crimea. He also opposes preventing Russia from conducting airstrikes in Syria, arguing that the United States should not get involved at all."],
    [4,28, "Stein has called for agreeing to treaties that would reduce the amount of nuclear weapons that both the United States and Russia have, and ban weapons in space. She has proposed that the United States rejoin the Anti-Ballistic Missile Treaty; she opposes a missile defense system in Eastern Europe."],
    [5,28, "McMullin vehemently opposes Putin's invasion of Ukraine. In addition to new sanctions against Russia, he supports non-recognition of Crimea as an annexed territory. He also accuses Putin's regime of committing war crimes in Syria."],
    [1,29, "On social issues, Clinton has adopted some liberal positions. Although she has evolved on issues surrounding the LGBT community, she has put her full support behind the LGBT movement. She pledges to build on President Obama's several executive orders on LGBT equality, and work with Congress to add gender identity and sexual orientation to the list of protected classes under the Civil Rights Act of 1964 (such as race, sex, religion, etc.). Her campaign website presents a lengthy list of reforms that she pledges to fight for, but in summary, she promises to continue President Obama's approach. She pledges to expand support and resources for Americans with disabilities, in accordance with the Americans with Disabilities Act. On abortion, she holds a clear pro-choice position, and supports federal funding of Planned Parenthood. She has called for the end of the Hyde Amendment, which provides federal funds for abortions in three cases: pregnancies that arise from incest and rape, and instances where the mother's life is in jeopardy."],
    [2,29, "Trump has pledged to protect the LGBT community, but his personal views have evolved on the issue. He currently favors judicial nominees who oppose the recent Supreme Court decisions that made LGBT marriage legal in all 50 states. Despite his socially conservative running mate, he has promoted a more laissez-faire approach - at least on the federal level - to the issue of transgender bathrooms. On abortion, he was 'very pro-choice' in 1999, but he has now adopted a pro-life posture. He has suggested support for the Hyde Amendment, which prohibits federal funding of abortions except in cases of rape, of incest, and where the mother's life is in jeopardy. While he has defended Planned Parenthood as a provider of women's health care services, he has indicated support for cutting federal funds to it over abortion."],
    [3,29, "Johnson favors LGBT marriage in all 50 states, citing his belief that government should neither regulate marriage nor belong in the bedroom. On disability issues, Johnson has stayed mum. He believes that issues pertaining to reproductive health and abortion must be handled at the state and local levels; and that decisions must ultimately be made by women themselves."],
    [4,29, "Stein has applauded the wave that made same-sex marriage legal in all 50 states, but now calls for a similar movement against discrimination in the workplace and housing. She recently tweeted that she supports 'complete reproductive healthcare, which includes the right to an abortion.'"],
    [5,29, "On abortion, McMullin is staunchly pro-life; he has stated that his judicial nominees would favor overturning Roe v. Wade. On LGBT marriage, he personally opposes it, but he accepts the Supreme Court’s decision to make it legal nationwide."],
    [1,30, "Clinton largely supports keeping Social Security as is; she opposes raising the retirement age, partial privatization, and reducing annual cost-of-living arrangements. She has argued that benefits should be expanded for low-income seniors, women, and caregivers. Furthermore, she favors increasing the current cap for higher-income Americans."],
    [2,30, "The GOP platform calls for tweaking Social Security for younger generations, considering reforms like raising the retirement age, partial privatization, and benefit cuts. In sharp disagreement with the platform - and his running mate - Trump proposes no changes to Social Security."],
    [3,30, "Johnson believes in continuing Social Security for people who have already paid into the system. For future participants, he supports raising the retirement age to 70 or 72, partial privatization, means testing for Social Security recipients, and changing the escalator built into Social Security from the wage index to inflation. Funding for the program would come from FairTax revenues."],
    [4,30, "Stein supports keeping Social Security as is, except for raising the cap for the rich. She vehemently opposes privatizing Social Security."],
    [5,30, nil],
    [1,31, "Clinton has argued that President Obama waited too long to begin arming and training so-called 'moderate' Syrian rebels, which she believed has contributed to the rise of ISIS and other radical terrorist groups. She has taken a hawkish position on Syria in the past, supporting President Obama's failed bid to seek congressional approval for airstrikes. She also led an effort to remove President Bashar al-Assad from power in 2011. Although she does not support deploying a significant amount of U.S. forces in Syria - preferring a ground force of Sunni Arabs and Kurds - she favors the use of Special Operations forces there, along with a no-fly zone that could provide a safe haven for refugees of the Syrian crisis."],
    [2,31, "Trump has stated that the United States should not get involved in the Syrian conflict, or at least militarily. But he has also vowed to 'knock the hell' out of ISIS; he opposes preventing Russian airstrikes in the region. Much of his other rhetoric on Syria pertains to the refugees. He favors negotiating with Gulf states to create a safe haven in Syria, but above all, he opposes bringing Syrian refugees into the United States."],
    [3,31, "Johnson argues that the United States should not get involved in the Syrian crisis; nor should it prevent Russia from conducting airstrikes in Syria."],
    [4,31, "Stein wants to pursue a diplomatic resolution to the ongoing Syria crisis. In 2012, she called for stopping the flow of arms to all sides of the conflict."],
    [5,31, "McMullin has stated that he wants to 'pick up the pace' in developing a more rigorous strategy. His stated goal is not only to engage in more airstrikes against ISIS and provide more military support to allies in the region, but also to limit the power of embattled strongman President Bashir al-Assad. He prefers that America use the CIA (in which he served) and Special Forces, and train local forces on the ground. But he does not rule out deploying American troops if necessary. Meanwhile, he wants to combat the 'unjustified hysteria' of many Americans with regard to Syrian refugees; he suggests that the United States will accept more of them."],
    [1,32, "Like President Obama, Clinton has proposed closing corporate and Wall Street tax loopholes and raising taxes on wealthier Americans. She has endorsed the so-called 'Buffett Rule', which demands that wealthier Americans pay a higher tax rate than middle-class families; she has proposed a 4-percent surcharge on Americans who make more than $5 million a year. She has also called for simpler and lower taxes for small businesses, and tax relief for expenses like out-of-pocket health care costs, family care, and other items. She opposes a flat-tax or FairTax system."],
    [2,32, "Trump proposes a tax reform package that relies on supply-side economics. He clearly prefers a simpler tax code, as he has stated as much since 2000, when he mulled an independent run for president. But the details have changed ever since, and quite often at that. While he has repeatedly expressed interest in tax hikes for wealthier Americans, including himself and hedge fund managers, he has also stated that he prefers lower taxes for all Americans. Either way, he has pledged that the 'rich will pay their fair share', as well as individuals and corporations whose repatriated money would be subject to a tax. His current proposal would reduce the number of income tax brackets from seven to three: 12 percent, 25 percent and 33 percent, along with a 0 percent tax rate for people making less than $25,000 per year. He also supports reducing the corporate/business income tax rate to 15 percent for every business; repealing the estate tax, the death tax, and the carried interest deduction; and making the average cost of childcare fully deductible. He also proposes that low-income taxpayers will be able to take a deduction against the payroll tax."],
    [3,32, "Johnson proposes scrapping the entire tax code and abolishing the IRS; he promotes a 23 percent national consumption tax, or FairTax."],
    [4,32, "Stein advocates for a more progressive tax code, one that would greatly increase capital gains, corporate, and inheritance taxes. She would greatly decrease payroll taxes and income taxes for lower-income families, and more slightly decrease income taxes on middle-income families. While she would maintain excise taxes on alcohol and cigarettes, she would greatly increase environmentally related taxes, namely taxes on pollution."],
    [5,32, "McMullin supports the House plan, which would reduce the number of income tax brackets from seven to three: 12 percent, 25 percent and 33 percent."],
    [1,33, "Clinton wants to increase access to capital for startups, increase technology and computer science education in public schools and elsewhere, and expand broadband coverage nationwide. She supports net neutrality, increasing cybersecurity, and the free flow of data across international borders. She has called for a government commission to examine the question of balancing Americans' privacy and the government's ability to access relevant data and metadata (as exemplified by the recent Apple/FBI dispute). Finally, she has called for an initiative to modernize the technology that the government itself uses."],
    [2,33, "Trump does not favor net neutrality, but he supports 'closing the parts of the Internet where ISIS is'. He also believes that government should be able to collect American metadata; for example, he supported the FBI in its dispute with Apple."],
    [3,33, "Johnson opposes net neutrality or any government intervention in the Internet. He is a skeptic of domestic surveillance programs and other methods through which the government can use technological means to collect Americans' data."],
    [4,33, "Stein supports net neutrality and opposes government intervention in the Internet."],
    [5,33, nil],
    [1,34, "Clinton indicated in her book Hard Choices that she favored a large, smart-power counterterrorism strategy as Secretary of State, one which diplomacy, law enforcement, sanctions, and other tools along with targeted drone strikes. She has made proposals in line with that strategy. For example, she supports putting pressure on relevant Gulf states like Saudi Arabia and Qatar to stop its citizens from funding extremist groups. Like President Obama, she supports closing Guantanamo Bay and opposes waterboarding and other forms of enhanced interrogation. With regard to domestic terrorism, she has called for creating 'integrated intelligence use' among all levels of law enforcement; 'strengthening communication' with other countries; and working with Silicon Valley to combat 'online radicalization'. She is open to expanding terrorist watch lists."],
    [2,34, "Trump has adopted a very tough position on combatting terrorism at home and abroad. While he has called for the end of 'nation-building', he has also called for working on counterterrorism strategies with international organizations like NATO. He is even open to working with Russia on defeating ISIS. Although he has called for 'unpredictability' and thus not discussed his proposed strategy at great length, he has stated that he would support a blend of military operations, cutting off terrorists' sources of funding, strengthened intelligence, and increased cyberwarfare. He has also cited his hardline immigration stance - namely his support for suspending immigration from areas 'where adequate screening cannot take place' - as another element in his counterterrorism strategy. Finally, he has indicated that he would keep the Guantanamo Bay facility open and support the use of waterboarding and other enhanced interrogation techniques. He has even called for murdering the families of terrorists, which critics have taken to mean that he would force the military to commit war crimes."],
    [3,34, "Johnson has argued that the federal government has a significant role to play in protecting Americans from terrorism. He has called for Congress to declare war on ISIS, but has not suggested much else as far as his administration's prospective counterterrorism strategy. He believes that the international community should cut off funding to ISIS. He has opposed the Patriot Act, torture, and Guantanamo Bay, though he is open to detaining ‘enemy combatants’ and subjecting them to military tribunals."],
    [4,34, "Stein has called for cutting off the supply of funds and arms to terrorist groups; for example, she proposes a weapons embargo to the Middle East. She has called on Gulf state allies to cease buying oil from the black market. She opposes the 'War on Terror' and Guantanamo Bay."],
    [5,34, "McMullin has called for the United States to 'pick up the pace' on combatting terrorist groups like ISIS. He has not specified a lot, but he has stated that he opposes waterboarding and supports keeping Guantanamo Bay open as long as necessary."],
    [1,35, "Clinton has adopted a more populist position on trade. She once said, 'Any trade deal has to produce jobs and raise wages and increase prosperity and protect our security.' In accordance with these standards, she now opposes the Trans-Pacific Partnership (TPP), even though she negotiated it as Secretary of State and once referred to it as the 'gold standard'. She pledges to re-negotiate the deal, along with NAFTA. Meanwhile, she supports the U.S. Export-Import Bank."],
    [2,35, "Trump's populist message has repeatedly critiqued the recent trade deals in which the United States has been involved. He opposes recent international trade agreements like the Trans-Pacific Partnership (TPP) and the World Trade Organization (WTO), from which he has threatened to withdraw; he also proposes to renegotiate NAFTA. He has repeatedly proposed tariffs on exports from China and Mexico, two of his favorite campaign targets. Specifically, he has proposed 15-35 percent tariffs on goods from companies that move their operations to Mexico, like Ford and Carrier."],
    [3,35, "Johnson supports free trade and completely opposes tariffs. He has been critical of trade deals that are 'just laden with crony capitalism', like NAFTA and the controversial Trans-Pacific Partnership (TPP). But he has also expressed reserved support for TPP."],
    [4,35, "Stein is a staunch skeptic of trade deals like NAFTA and the controversial Trans-Pacific Partnership (TPP). Her platform calls for replacing them and 'other corporate free trade agreements' with fair trade laws 'that benefits local workers and communities'."],
    [5,35, "McMullin supports international trade deals like the Trans-Pacific Partnership (TPP), but he also recognizes the protectionist and populist strain running through his party. In order to combat the negative effects of international trade deals on American works, he has suggested apprenticeship programs."],
    [1,36, "Clinton vehemently opposes privatizing veterans' services, especially the VA. Instead, she supports streamlining existing VA systems and increasing federal funding for programs that will help veterans and their families. These include military-specific health research and services, job training programs, and others. In short, she wants to strengthen the 'Post-9/11 G.I. Bill' and implement a new 'Bradley Plan', which provided a range of health and readjustment services to veterans returning from service in World War II."],
    [2,36, "Trump has repeatedly critiqued the Obama administration over the VA's recent scandals, especially the long wait times. Only recently has he presented a plan, which prioritizes an overhaul of the VA in a way that makes it a more privatized system with increased public funding. Under the proposal, all veterans would be able to bring their veteran's ID card to any physician or hospital of their choice. The government would fund veteran health services from both VA and private facilities. The plan also calls for expanding VA resources, including: equipping VA hospitals with OBYGN and other women's health services, embedding VA clinics in rural and other underserved areas, and research on veteran-specific services like PTSD and traumatic injury treatment. When it comes to personnel, he has demanded that top personnel at the organization who have 'enabled or overlooked corruption and incompetence' lose their job security, and their jobs; the official policy position contains the words: 'They're fired.' He has encouraged the hiring of more veterans to work at the VA and enhancing servicemen's readjustment programs."],
    [3,36, nil],
    [4,36, nil],
    [5,36, "Largely mum. Although, he indicates, 'Veterans should be free to choose the health care that best suits their needs - regardless of where it comes from."],
  ]

  positions.each do | a, b, c |
    Position.create(candidate_id: a, issue_id: b, position: c)
  end

end